#
# Makefile for the SWAP
#

obj-$(CONFIG_SWAP_DA) += \
         buffer/ \
         ksyms/ \
         driver/ \
         writer/ \
         kprobe/ \
         uprobe/ \
         us_manager/ \
         ks_features/ \
         sampler/ \
         energy/ \
         parser/
