name: Kernel CI (SM-Z130H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1
        sudo git clone --depth 1 --branch android-4.4.4_r2.0.1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7 /opt/toolchains/arm-eabi-4.7/

    - name: Building Kernel (cm-12.1)
      run: |
        git clone https://github.com/NotNoelChannel/android_kernel_samsung_kiran/ -b cm-12.1 ~/android_kernel_samsung_kiran
        cd ~/android_kernel_samsung_kiran
        wget https://gitlab.com/postmarketOS/pmaports/-/raw/master/device/testing/linux-samsung-kiran/0001-kiran-initramfs.patch
        wget https://gitlab.com/postmarketOS/pmaports/-/raw/master/device/testing/linux-samsung-kiran/0003-mmc-card-not-access-RPMB-partition-for-normal-read-and-write.patch
        wget https://gitlab.com/postmarketOS/pmaports/-/raw/master/device/testing/linux-samsung-kiran/0004-sprdfb-fix-mmap-address.patch
        patch -p1 < 0001-kiran-initramfs.patch
        patch -p1 < 0003-mmc-card-not-access-RPMB-partition-for-normal-read-and-write.patch
        patch -p1 < 0004-sprdfb-fix-mmap-address.patch
        export CROSS_COMPILE=/opt/toolchains/arm-eabi-4.7/bin/arm-eabi-
        export RELEASE_DATE=`date +%Y%m%d`
        export BOOT_PATH="arch/arm/boot"
        export DZIMAGE="dzImage"
        wget https://gitlab.com/Grimler/dtbtool-sprd/-/raw/master/dtbtool.c
        gcc dtbtool.c -o dtbtool
        wget https://github.com/ne0z/tizen_system_tools/raw/refs/heads/master/mkdzimage
        make ARCH=arm tizen_kiran_defconfig
        make -j12 zImage ARCH=arm
        export DTC_PATH="scripts/dtc"
        rm $BOOT_PATH/dts/*.dtb -f
        make ARCH=arm dtbs 
        chmod +x ./dtbtool
        chmod +x ./mkdzimage
        ./dtbtool -o $BOOT_PATH/merged-dtb -p $DTC_PATH -v $BOOT_PATH/dts
        ./mkdzimage -o $BOOT_PATH/$DZIMAGE -k $BOOT_PATH/zImage -d $BOOT_PATH/merged-dtb
        echo Done!
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp ~/android_kernel_samsung_kiran/arch/arm/boot/dzImage /home/runner/work/output/mkdzImage
        cp ~/android_kernel_samsung_kiran/arch/arm/boot/merged-dtb /home/runner/work/output/dtb
        find . -name "*.ko" -exec cp {} /home/runner/work/output/ \;  
    - name: Uploading Tizen image
      uses: actions/upload-artifact@v3
      with:
        name: mkdzImage
        path: /home/runner/work/output/mkdzImage
    - name: Uploading dt.img
      uses: actions/upload-artifact@v3
      with:
        name: dtb
        path: /home/runner/work/output/dtb
    - name: Uploading zImage if exist
      uses: actions/upload-artifact@v3
      with:
        name: zImage
        path: ~/android_kernel_samsung_kiran/arch/arm/boot/zImage
    - name: Uploading Modules
      uses: actions/upload-artifact@v3
      with:
        name: modules
        path: /home/runner/work/output/*.ko
